// Package client generates a typed TypeScript client from a validated
// manifest's schema model. The manifest is the single shared artifact between
// the Go backend and any TypeScript frontend: this package never reads or
// writes Go structs or hand-maintained TS interfaces, only the schema model
// that validate.Manifest already proved safe to serve.
//
// Generation is a pure function of the schema model: the same *schema.App
// always produces byte-identical output, so regenerating for an unchanged
// manifest is a no-op diff.
package client

import (
	"fmt"
	"strings"

	"pocketknife/schema"
)

// Generate renders a complete, self-contained TypeScript module for app: types
// for every entity mirroring the closed field-type set, and a typed client
// class exposing exactly the CRUD/list operations the entity's manifest
// enables — matching the URL scheme, query syntax, JSON shapes and error
// envelope of the generic HTTP API byte-for-byte.
func Generate(app *schema.App) []byte {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by pocketknife from the %q manifest (app id %q, schema version %d).\n", app.Name, app.ID, app.Version)
	b.WriteString("// DO NOT EDIT — regenerate from the manifest instead.\n\n")
	b.WriteString(preamble)

	for _, ent := range app.Entities {
		writeEntity(&b, app, ent)
	}

	writeRootClient(&b, app)

	return []byte(b.String())
}

// preamble is the fixed runtime support emitted once per generated module: the
// error type, the list-result envelope and the small request/query helpers
// every entity client shares.
const preamble = `export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", ` + "`${field}:${op}:${String(value)}`" + `);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? ` + "`?${qs}`" + ` : "";
}

`

// fieldTSType returns the TypeScript type for a field's own value (never
// including null — callers add "| null" where the field is optional).
func fieldTSType(ent *schema.Entity, f *schema.Field) string {
	switch f.Type {
	case schema.TypeText, schema.TypeDatetime, schema.TypeReference:
		if f.Type == schema.TypeDatetime {
			return "ISODateTime"
		}
		return "string"
	case schema.TypeInteger, schema.TypeReal:
		return "number"
	case schema.TypeBoolean:
		return "boolean"
	case schema.TypeEnum:
		return enumTypeName(ent, f)
	default:
		return "unknown"
	}
}

// outputFieldType is the type of a field as it appears in a returned row:
// nullable whenever the field is not required (an absent, non-defaulted value
// is stored and emitted as null).
func outputFieldType(ent *schema.Entity, f *schema.Field) string {
	t := fieldTSType(ent, f)
	if !f.Required {
		return t + " | null"
	}
	return t
}

func writeEntity(b *strings.Builder, app *schema.App, ent *schema.Entity) {
	typeName := pascalCase(ent.Name)
	fmt.Fprintf(b, "// --- entity: %s ---\n\n", ent.Name)

	for _, f := range ent.Fields {
		if f.Type == schema.TypeEnum {
			fmt.Fprintf(b, "export type %s = %s;\n\n", enumTypeName(ent, f), enumLiteralUnion(f))
		}
	}

	// Row type: platform columns plus every declared field, in manifest order.
	fmt.Fprintf(b, "export interface %s {\n", typeName)
	b.WriteString("  id: string;\n")
	b.WriteString("  created_at: ISODateTime;\n")
	b.WriteString("  updated_at: ISODateTime;\n")
	for _, f := range ent.Fields {
		fmt.Fprintf(b, "  %s: %s;\n", f.Name, outputFieldType(ent, f))
	}
	b.WriteString("}\n\n")

	if ent.Allows(schema.OpCreate) {
		writeInputType(b, ent, typeName+"CreateInput", true)
	}
	if ent.Allows(schema.OpUpdate) {
		writeInputType(b, ent, typeName+"UpdateInput", false)
	}

	if ent.Allows(schema.OpRead) {
		writeListTypes(b, ent, typeName)
	}

	writeEntityClient(b, app, ent, typeName)
}

// writeInputType renders the CreateInput or UpdateInput shape. forCreate
// controls whether a required-without-default field is a mandatory key
// (create) or always optional (a partial update never requires a field).
func writeInputType(b *strings.Builder, ent *schema.Entity, name string, forCreate bool) {
	fmt.Fprintf(b, "export interface %s {\n", name)
	for _, f := range ent.Fields {
		t := fieldTSType(ent, f)
		optional := true
		if !f.Required {
			t += " | null"
		}
		if forCreate && f.Required && !f.HasDefault {
			optional = false
		}
		if optional {
			fmt.Fprintf(b, "  %s?: %s;\n", f.Name, t)
		} else {
			fmt.Fprintf(b, "  %s: %s;\n", f.Name, t)
		}
	}
	b.WriteString("}\n\n")
}

// writeListTypes renders the filterable/sortable field unions and the list
// params shape, mirroring api.resolveColumn: every declared field plus the
// three platform columns are queryable.
func writeListTypes(b *strings.Builder, ent *schema.Entity, typeName string) {
	fields := make([]string, 0, len(ent.Fields)+3)
	fields = append(fields, "id", "created_at", "updated_at")
	for _, f := range ent.Fields {
		fields = append(fields, f.Name)
	}
	quoted := make([]string, len(fields))
	for i, f := range fields {
		quoted[i] = fmt.Sprintf("%q", f)
	}
	fieldUnion := typeName + "FilterableField"
	fmt.Fprintf(b, "export type %s = %s;\n\n", fieldUnion, strings.Join(quoted, " | "))
	fmt.Fprintf(b, "export type %sSortField = %s | `-${%s}`;\n\n", typeName, fieldUnion, fieldUnion)

	fmt.Fprintf(b, "export interface %sListParams {\n", typeName)
	fmt.Fprintf(b, "  filter?: Array<readonly [%s, FilterOp, string | number | boolean]>;\n", fieldUnion)
	fmt.Fprintf(b, "  sort?: %sSortField[];\n", typeName)
	b.WriteString("  limit?: number;\n")
	b.WriteString("  offset?: number;\n")
	b.WriteString("}\n\n")
}

func writeEntityClient(b *strings.Builder, app *schema.App, ent *schema.Entity, typeName string) {
	className := typeName + "Client"
	base := fmt.Sprintf("/apps/%s/%s", app.ID, ent.Name)

	fmt.Fprintf(b, "export class %s {\n", className)
	b.WriteString("  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}\n\n")

	if ent.Allows(schema.OpCreate) {
		fmt.Fprintf(b, "  create(input: %sCreateInput): Promise<%s> {\n", typeName, typeName)
		fmt.Fprintf(b, "    return request(this.baseUrl, this.fetchImpl, \"POST\", %q, input);\n", base)
		b.WriteString("  }\n\n")
	}
	if ent.Allows(schema.OpRead) {
		fmt.Fprintf(b, "  get(id: string): Promise<%s> {\n", typeName)
		fmt.Fprintf(b, "    return request(this.baseUrl, this.fetchImpl, \"GET\", `%s/${encodeURIComponent(id)}`);\n", base)
		b.WriteString("  }\n\n")

		fmt.Fprintf(b, "  list(params?: %sListParams): Promise<ListResult<%s>> {\n", typeName, typeName)
		fmt.Fprintf(b, "    return request(this.baseUrl, this.fetchImpl, \"GET\", `%s${buildQuery(params)}`);\n", base)
		b.WriteString("  }\n\n")
	}
	if ent.Allows(schema.OpUpdate) {
		fmt.Fprintf(b, "  update(id: string, input: %sUpdateInput): Promise<%s> {\n", typeName, typeName)
		fmt.Fprintf(b, "    return request(this.baseUrl, this.fetchImpl, \"PATCH\", `%s/${encodeURIComponent(id)}`, input);\n", base)
		b.WriteString("  }\n\n")
	}
	if ent.Allows(schema.OpDelete) {
		fmt.Fprintf(b, "  delete(id: string): Promise<void> {\n")
		fmt.Fprintf(b, "    return request(this.baseUrl, this.fetchImpl, \"DELETE\", `%s/${encodeURIComponent(id)}`);\n", base)
		b.WriteString("  }\n\n")
	}
	b.WriteString("}\n\n")
}

func writeRootClient(b *strings.Builder, app *schema.App) {
	className := pascalCase(app.ID) + "Client"
	fmt.Fprintf(b, "export class %s {\n", className)
	for _, ent := range app.Entities {
		fmt.Fprintf(b, "  readonly %s: %sClient;\n", ent.Name, pascalCase(ent.Name))
	}
	b.WriteString("\n  constructor(options: ClientOptions = {}) {\n")
	b.WriteString("    const baseUrl = options.baseUrl ?? \"\";\n")
	b.WriteString("    const fetchImpl = options.fetch ?? fetch;\n")
	for _, ent := range app.Entities {
		fmt.Fprintf(b, "    this.%s = new %sClient(baseUrl, fetchImpl);\n", ent.Name, pascalCase(ent.Name))
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")
}

func enumTypeName(ent *schema.Entity, f *schema.Field) string {
	return pascalCase(ent.Name) + pascalCase(f.Name)
}

func enumLiteralUnion(f *schema.Field) string {
	quoted := make([]string, len(f.Values))
	for i, v := range f.Values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, " | ")
}

// pascalCase converts a manifest machine name (^[a-z][a-z0-9_]*$) into a
// TypeScript-identifier-safe PascalCase name, e.g. "activity_log" -> "ActivityLog".
func pascalCase(name string) string {
	parts := strings.Split(name, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}
