// Code generated by the pocketknife agent's stub validator from the "Coffee Tracker" manifest (app id "espresso_tracker", schema version 2).
// DO NOT EDIT — regenerate from the manifest instead.

export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", `${field}:${op}:${String(value)}`);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? `?${qs}` : "";
}

// --- entity: bean ---

export interface Bean {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  name: string;
  roaster: string | null;
  roast_date: ISODateTime | null;
  notes: string | null;
}

export interface BeanCreateInput {
  name: string;
  roaster?: string | null;
  roast_date?: ISODateTime | null;
  notes?: string | null;
}

export interface BeanUpdateInput {
  name?: string;
  roaster?: string | null;
  roast_date?: ISODateTime | null;
  notes?: string | null;
}

export type BeanFilterableField = "id" | "created_at" | "updated_at" | "name" | "roaster" | "roast_date" | "notes";

export type BeanSortField = BeanFilterableField | `-${BeanFilterableField}`;

export interface BeanListParams {
  filter?: Array<readonly [BeanFilterableField, FilterOp, string | number | boolean]>;
  sort?: BeanSortField[];
  limit?: number;
  offset?: number;
}

export class BeanClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: BeanCreateInput): Promise<Bean> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/espresso_tracker/bean", input);
  }

  get(id: string): Promise<Bean> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/espresso_tracker/bean/${encodeURIComponent(id)}`);
  }

  list(params?: BeanListParams): Promise<ListResult<Bean>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/espresso_tracker/bean${buildQuery(params)}`);
  }

  update(id: string, input: BeanUpdateInput): Promise<Bean> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/espresso_tracker/bean/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/espresso_tracker/bean/${encodeURIComponent(id)}`);
  }

}

// --- entity: brew ---

export type BrewMethod = "espresso" | "aeropress";

export interface Brew {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  method: BrewMethod;
  bean: string | null;
  dose_g: number;
  output_g: number | null;
  brew_time_s: number | null;
  grind_setting: string | null;
  water_temp_c: number | null;
  inverted: boolean | null;
  rating: number | null;
  notes: string | null;
}

export interface BrewCreateInput {
  method?: BrewMethod;
  bean?: string | null;
  dose_g: number;
  output_g?: number | null;
  brew_time_s?: number | null;
  grind_setting?: string | null;
  water_temp_c?: number | null;
  inverted?: boolean | null;
  rating?: number | null;
  notes?: string | null;
}

export interface BrewUpdateInput {
  method?: BrewMethod;
  bean?: string | null;
  dose_g?: number;
  output_g?: number | null;
  brew_time_s?: number | null;
  grind_setting?: string | null;
  water_temp_c?: number | null;
  inverted?: boolean | null;
  rating?: number | null;
  notes?: string | null;
}

export type BrewFilterableField = "id" | "created_at" | "updated_at" | "method" | "bean" | "dose_g" | "output_g" | "brew_time_s" | "grind_setting" | "water_temp_c" | "inverted" | "rating" | "notes";

export type BrewSortField = BrewFilterableField | `-${BrewFilterableField}`;

export interface BrewListParams {
  filter?: Array<readonly [BrewFilterableField, FilterOp, string | number | boolean]>;
  sort?: BrewSortField[];
  limit?: number;
  offset?: number;
}

export class BrewClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: BrewCreateInput): Promise<Brew> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/espresso_tracker/brew", input);
  }

  get(id: string): Promise<Brew> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/espresso_tracker/brew/${encodeURIComponent(id)}`);
  }

  list(params?: BrewListParams): Promise<ListResult<Brew>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/espresso_tracker/brew${buildQuery(params)}`);
  }

  update(id: string, input: BrewUpdateInput): Promise<Brew> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/espresso_tracker/brew/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/espresso_tracker/brew/${encodeURIComponent(id)}`);
  }

}

export class EspressoTrackerClient {
  readonly bean: BeanClient;
  readonly brew: BrewClient;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "";
    const fetchImpl = options.fetch ?? fetch;
    this.bean = new BeanClient(baseUrl, fetchImpl);
    this.brew = new BrewClient(baseUrl, fetchImpl);
  }
}
