// Code generated by the pocketknife agent's stub validator from the "Günther Schätzer" manifest (app id "guenther_schaetzer", schema version 1).
// DO NOT EDIT — regenerate from the manifest instead.

export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", `${field}:${op}:${String(value)}`);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? `?${qs}` : "";
}

// --- entity: question ---

export type QuestionCategory = "stadion" | "tore" | "karten" | "vereine" | "transfers" | "punkte" | "geschichte" | "international";

export type QuestionDifficulty = "leicht" | "mittel" | "schwer";

export interface Question {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  text: string;
  correct_answer: number;
  unit: string | null;
  category: QuestionCategory;
  difficulty: QuestionDifficulty;
  hint: string | null;
}

export interface QuestionCreateInput {
  text: string;
  correct_answer: number;
  unit?: string | null;
  category: QuestionCategory;
  difficulty: QuestionDifficulty;
  hint?: string | null;
}

export interface QuestionUpdateInput {
  text?: string;
  correct_answer?: number;
  unit?: string | null;
  category?: QuestionCategory;
  difficulty?: QuestionDifficulty;
  hint?: string | null;
}

export type QuestionFilterableField = "id" | "created_at" | "updated_at" | "text" | "correct_answer" | "unit" | "category" | "difficulty" | "hint";

export type QuestionSortField = QuestionFilterableField | `-${QuestionFilterableField}`;

export interface QuestionListParams {
  filter?: Array<readonly [QuestionFilterableField, FilterOp, string | number | boolean]>;
  sort?: QuestionSortField[];
  limit?: number;
  offset?: number;
}

export class QuestionClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: QuestionCreateInput): Promise<Question> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/guenther_schaetzer/question", input);
  }

  get(id: string): Promise<Question> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/guenther_schaetzer/question/${encodeURIComponent(id)}`);
  }

  list(params?: QuestionListParams): Promise<ListResult<Question>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/guenther_schaetzer/question${buildQuery(params)}`);
  }

  update(id: string, input: QuestionUpdateInput): Promise<Question> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/guenther_schaetzer/question/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/guenther_schaetzer/question/${encodeURIComponent(id)}`);
  }

}

// --- entity: game ---

export type GameStatus = "active" | "finished";

export interface Game {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  player1_name: string;
  player2_name: string;
  question_count: number;
  status: GameStatus;
  player1_score: number;
  player2_score: number;
  current_round: number;
}

export interface GameCreateInput {
  player1_name: string;
  player2_name: string;
  question_count?: number;
  status?: GameStatus;
  player1_score?: number;
  player2_score?: number;
  current_round?: number;
}

export interface GameUpdateInput {
  player1_name?: string;
  player2_name?: string;
  question_count?: number;
  status?: GameStatus;
  player1_score?: number;
  player2_score?: number;
  current_round?: number;
}

export type GameFilterableField = "id" | "created_at" | "updated_at" | "player1_name" | "player2_name" | "question_count" | "status" | "player1_score" | "player2_score" | "current_round";

export type GameSortField = GameFilterableField | `-${GameFilterableField}`;

export interface GameListParams {
  filter?: Array<readonly [GameFilterableField, FilterOp, string | number | boolean]>;
  sort?: GameSortField[];
  limit?: number;
  offset?: number;
}

export class GameClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: GameCreateInput): Promise<Game> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/guenther_schaetzer/game", input);
  }

  get(id: string): Promise<Game> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/guenther_schaetzer/game/${encodeURIComponent(id)}`);
  }

  list(params?: GameListParams): Promise<ListResult<Game>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/guenther_schaetzer/game${buildQuery(params)}`);
  }

  update(id: string, input: GameUpdateInput): Promise<Game> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/guenther_schaetzer/game/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/guenther_schaetzer/game/${encodeURIComponent(id)}`);
  }

}

// --- entity: round ---

export type RoundStatus = "waiting_p1" | "waiting_p2" | "revealed";

export type RoundWinner = "player1" | "player2" | "tie";

export interface Round {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  game: string;
  question: string;
  round_number: number;
  player1_guess: number | null;
  player2_guess: number | null;
  status: RoundStatus;
  winner: RoundWinner | null;
}

export interface RoundCreateInput {
  game: string;
  question: string;
  round_number: number;
  player1_guess?: number | null;
  player2_guess?: number | null;
  status?: RoundStatus;
  winner?: RoundWinner | null;
}

export interface RoundUpdateInput {
  game?: string;
  question?: string;
  round_number?: number;
  player1_guess?: number | null;
  player2_guess?: number | null;
  status?: RoundStatus;
  winner?: RoundWinner | null;
}

export type RoundFilterableField = "id" | "created_at" | "updated_at" | "game" | "question" | "round_number" | "player1_guess" | "player2_guess" | "status" | "winner";

export type RoundSortField = RoundFilterableField | `-${RoundFilterableField}`;

export interface RoundListParams {
  filter?: Array<readonly [RoundFilterableField, FilterOp, string | number | boolean]>;
  sort?: RoundSortField[];
  limit?: number;
  offset?: number;
}

export class RoundClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: RoundCreateInput): Promise<Round> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/guenther_schaetzer/round", input);
  }

  get(id: string): Promise<Round> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/guenther_schaetzer/round/${encodeURIComponent(id)}`);
  }

  list(params?: RoundListParams): Promise<ListResult<Round>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/guenther_schaetzer/round${buildQuery(params)}`);
  }

  update(id: string, input: RoundUpdateInput): Promise<Round> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/guenther_schaetzer/round/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/guenther_schaetzer/round/${encodeURIComponent(id)}`);
  }

}

export class GuentherSchaetzerClient {
  readonly question: QuestionClient;
  readonly game: GameClient;
  readonly round: RoundClient;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "";
    const fetchImpl = options.fetch ?? fetch;
    this.question = new QuestionClient(baseUrl, fetchImpl);
    this.game = new GameClient(baseUrl, fetchImpl);
    this.round = new RoundClient(baseUrl, fetchImpl);
  }
}
