// Code generated by the pocketknife agent's stub validator from the "Babyentwicklung" manifest (app id "baby_tracker", schema version 1).
// DO NOT EDIT — regenerate from the manifest instead.

export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", `${field}:${op}:${String(value)}`);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? `?${qs}` : "";
}

// --- entity: baby ---

export interface Baby {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  name: string;
  geburtsdatum: ISODateTime;
}

export interface BabyCreateInput {
  name: string;
  geburtsdatum: ISODateTime;
}

export interface BabyUpdateInput {
  name?: string;
  geburtsdatum?: ISODateTime;
}

export type BabyFilterableField = "id" | "created_at" | "updated_at" | "name" | "geburtsdatum";

export type BabySortField = BabyFilterableField | `-${BabyFilterableField}`;

export interface BabyListParams {
  filter?: Array<readonly [BabyFilterableField, FilterOp, string | number | boolean]>;
  sort?: BabySortField[];
  limit?: number;
  offset?: number;
}

export class BabyClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: BabyCreateInput): Promise<Baby> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/baby_tracker/baby", input);
  }

  get(id: string): Promise<Baby> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/baby/${encodeURIComponent(id)}`);
  }

  list(params?: BabyListParams): Promise<ListResult<Baby>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/baby${buildQuery(params)}`);
  }

  update(id: string, input: BabyUpdateInput): Promise<Baby> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/baby_tracker/baby/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/baby_tracker/baby/${encodeURIComponent(id)}`);
  }

}

// --- entity: sprung ---

export interface Sprung {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  nummer: number;
  bezeichnung: string;
  thema: string;
  startwoche: number;
  endwoche: number;
  beschreibung: string | null;
}

export interface SprungCreateInput {
  nummer: number;
  bezeichnung: string;
  thema: string;
  startwoche: number;
  endwoche: number;
  beschreibung?: string | null;
}

export interface SprungUpdateInput {
  nummer?: number;
  bezeichnung?: string;
  thema?: string;
  startwoche?: number;
  endwoche?: number;
  beschreibung?: string | null;
}

export type SprungFilterableField = "id" | "created_at" | "updated_at" | "nummer" | "bezeichnung" | "thema" | "startwoche" | "endwoche" | "beschreibung";

export type SprungSortField = SprungFilterableField | `-${SprungFilterableField}`;

export interface SprungListParams {
  filter?: Array<readonly [SprungFilterableField, FilterOp, string | number | boolean]>;
  sort?: SprungSortField[];
  limit?: number;
  offset?: number;
}

export class SprungClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: SprungCreateInput): Promise<Sprung> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/baby_tracker/sprung", input);
  }

  get(id: string): Promise<Sprung> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/sprung/${encodeURIComponent(id)}`);
  }

  list(params?: SprungListParams): Promise<ListResult<Sprung>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/sprung${buildQuery(params)}`);
  }

  update(id: string, input: SprungUpdateInput): Promise<Sprung> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/baby_tracker/sprung/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/baby_tracker/sprung/${encodeURIComponent(id)}`);
  }

}

// --- entity: faehigkeit ---

export type FaehigkeitKategorie = "motorik" | "sprache" | "soziales" | "wahrnehmung" | "emotion";

export interface Faehigkeit {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  sprung_id: string;
  bezeichnung: string;
  kategorie: FaehigkeitKategorie;
  beschreibung: string | null;
}

export interface FaehigkeitCreateInput {
  sprung_id: string;
  bezeichnung: string;
  kategorie: FaehigkeitKategorie;
  beschreibung?: string | null;
}

export interface FaehigkeitUpdateInput {
  sprung_id?: string;
  bezeichnung?: string;
  kategorie?: FaehigkeitKategorie;
  beschreibung?: string | null;
}

export type FaehigkeitFilterableField = "id" | "created_at" | "updated_at" | "sprung_id" | "bezeichnung" | "kategorie" | "beschreibung";

export type FaehigkeitSortField = FaehigkeitFilterableField | `-${FaehigkeitFilterableField}`;

export interface FaehigkeitListParams {
  filter?: Array<readonly [FaehigkeitFilterableField, FilterOp, string | number | boolean]>;
  sort?: FaehigkeitSortField[];
  limit?: number;
  offset?: number;
}

export class FaehigkeitClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: FaehigkeitCreateInput): Promise<Faehigkeit> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/baby_tracker/faehigkeit", input);
  }

  get(id: string): Promise<Faehigkeit> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/faehigkeit/${encodeURIComponent(id)}`);
  }

  list(params?: FaehigkeitListParams): Promise<ListResult<Faehigkeit>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/faehigkeit${buildQuery(params)}`);
  }

  update(id: string, input: FaehigkeitUpdateInput): Promise<Faehigkeit> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/baby_tracker/faehigkeit/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/baby_tracker/faehigkeit/${encodeURIComponent(id)}`);
  }

}

// --- entity: beobachtung ---

export interface Beobachtung {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  faehigkeit_id: string;
  datum: ISODateTime;
  notiz: string | null;
}

export interface BeobachtungCreateInput {
  faehigkeit_id: string;
  datum: ISODateTime;
  notiz?: string | null;
}

export interface BeobachtungUpdateInput {
  faehigkeit_id?: string;
  datum?: ISODateTime;
  notiz?: string | null;
}

export type BeobachtungFilterableField = "id" | "created_at" | "updated_at" | "faehigkeit_id" | "datum" | "notiz";

export type BeobachtungSortField = BeobachtungFilterableField | `-${BeobachtungFilterableField}`;

export interface BeobachtungListParams {
  filter?: Array<readonly [BeobachtungFilterableField, FilterOp, string | number | boolean]>;
  sort?: BeobachtungSortField[];
  limit?: number;
  offset?: number;
}

export class BeobachtungClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: BeobachtungCreateInput): Promise<Beobachtung> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/baby_tracker/beobachtung", input);
  }

  get(id: string): Promise<Beobachtung> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/beobachtung/${encodeURIComponent(id)}`);
  }

  list(params?: BeobachtungListParams): Promise<ListResult<Beobachtung>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/beobachtung${buildQuery(params)}`);
  }

  update(id: string, input: BeobachtungUpdateInput): Promise<Beobachtung> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/baby_tracker/beobachtung/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/baby_tracker/beobachtung/${encodeURIComponent(id)}`);
  }

}

// --- entity: tagebuch ---

export interface Tagebuch {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  datum: ISODateTime;
  eintrag: string;
  sprung_id: string | null;
}

export interface TagebuchCreateInput {
  datum: ISODateTime;
  eintrag: string;
  sprung_id?: string | null;
}

export interface TagebuchUpdateInput {
  datum?: ISODateTime;
  eintrag?: string;
  sprung_id?: string | null;
}

export type TagebuchFilterableField = "id" | "created_at" | "updated_at" | "datum" | "eintrag" | "sprung_id";

export type TagebuchSortField = TagebuchFilterableField | `-${TagebuchFilterableField}`;

export interface TagebuchListParams {
  filter?: Array<readonly [TagebuchFilterableField, FilterOp, string | number | boolean]>;
  sort?: TagebuchSortField[];
  limit?: number;
  offset?: number;
}

export class TagebuchClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: TagebuchCreateInput): Promise<Tagebuch> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/baby_tracker/tagebuch", input);
  }

  get(id: string): Promise<Tagebuch> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/tagebuch/${encodeURIComponent(id)}`);
  }

  list(params?: TagebuchListParams): Promise<ListResult<Tagebuch>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/baby_tracker/tagebuch${buildQuery(params)}`);
  }

  update(id: string, input: TagebuchUpdateInput): Promise<Tagebuch> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/baby_tracker/tagebuch/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/baby_tracker/tagebuch/${encodeURIComponent(id)}`);
  }

}

export class BabyTrackerClient {
  readonly baby: BabyClient;
  readonly sprung: SprungClient;
  readonly faehigkeit: FaehigkeitClient;
  readonly beobachtung: BeobachtungClient;
  readonly tagebuch: TagebuchClient;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "";
    const fetchImpl = options.fetch ?? fetch;
    this.baby = new BabyClient(baseUrl, fetchImpl);
    this.sprung = new SprungClient(baseUrl, fetchImpl);
    this.faehigkeit = new FaehigkeitClient(baseUrl, fetchImpl);
    this.beobachtung = new BeobachtungClient(baseUrl, fetchImpl);
    this.tagebuch = new TagebuchClient(baseUrl, fetchImpl);
  }
}
