// Code generated by pocketknife from the "Gratitude Log" manifest (app id "gratitude_log", schema version 1).
// DO NOT EDIT — regenerate from the manifest instead.

export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", `${field}:${op}:${String(value)}`);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? `?${qs}` : "";
}

// --- entity: entry ---

export interface Entry {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  text: string;
}

export interface EntryCreateInput {
  text: string;
}

export type EntryFilterableField = "id" | "created_at" | "updated_at" | "text";

export type EntrySortField = EntryFilterableField | `-${EntryFilterableField}`;

export interface EntryListParams {
  filter?: Array<readonly [EntryFilterableField, FilterOp, string | number | boolean]>;
  sort?: EntrySortField[];
  limit?: number;
  offset?: number;
}

export class EntryClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: EntryCreateInput): Promise<Entry> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/gratitude_log/entry", input);
  }

  get(id: string): Promise<Entry> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/gratitude_log/entry/${encodeURIComponent(id)}`);
  }

  list(params?: EntryListParams): Promise<ListResult<Entry>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/gratitude_log/entry${buildQuery(params)}`);
  }

}

export class GratitudeLogClient {
  readonly entry: EntryClient;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "";
    const fetchImpl = options.fetch ?? fetch;
    this.entry = new EntryClient(baseUrl, fetchImpl);
  }
}
