// Code generated by pocketknife from the "Tasks" manifest (app id "tasks", schema version 1).
// DO NOT EDIT — regenerate from the manifest instead.

export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", `${field}:${op}:${String(value)}`);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? `?${qs}` : "";
}

// --- entity: project ---

export interface Project {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  name: string;
}

export interface ProjectCreateInput {
  name: string;
}

export interface ProjectUpdateInput {
  name?: string;
}

export type ProjectFilterableField = "id" | "created_at" | "updated_at" | "name";

export type ProjectSortField = ProjectFilterableField | `-${ProjectFilterableField}`;

export interface ProjectListParams {
  filter?: Array<readonly [ProjectFilterableField, FilterOp, string | number | boolean]>;
  sort?: ProjectSortField[];
  limit?: number;
  offset?: number;
}

export class ProjectClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: ProjectCreateInput): Promise<Project> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/tasks/project", input);
  }

  get(id: string): Promise<Project> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/tasks/project/${encodeURIComponent(id)}`);
  }

  list(params?: ProjectListParams): Promise<ListResult<Project>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/tasks/project${buildQuery(params)}`);
  }

  update(id: string, input: ProjectUpdateInput): Promise<Project> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/tasks/project/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/tasks/project/${encodeURIComponent(id)}`);
  }

}

// --- entity: task ---

export type TaskPriority = "low" | "medium" | "high";

export interface Task {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  title: string;
  project: string | null;
  priority: TaskPriority | null;
  due: ISODateTime | null;
}

export interface TaskCreateInput {
  title: string;
  project?: string | null;
  priority?: TaskPriority | null;
  due?: ISODateTime | null;
}

export interface TaskUpdateInput {
  title?: string;
  project?: string | null;
  priority?: TaskPriority | null;
  due?: ISODateTime | null;
}

export type TaskFilterableField = "id" | "created_at" | "updated_at" | "title" | "project" | "priority" | "due";

export type TaskSortField = TaskFilterableField | `-${TaskFilterableField}`;

export interface TaskListParams {
  filter?: Array<readonly [TaskFilterableField, FilterOp, string | number | boolean]>;
  sort?: TaskSortField[];
  limit?: number;
  offset?: number;
}

export class TaskClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: TaskCreateInput): Promise<Task> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/tasks/task", input);
  }

  get(id: string): Promise<Task> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/tasks/task/${encodeURIComponent(id)}`);
  }

  list(params?: TaskListParams): Promise<ListResult<Task>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/tasks/task${buildQuery(params)}`);
  }

  update(id: string, input: TaskUpdateInput): Promise<Task> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/tasks/task/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/tasks/task/${encodeURIComponent(id)}`);
  }

}

export class TasksClient {
  readonly project: ProjectClient;
  readonly task: TaskClient;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "";
    const fetchImpl = options.fetch ?? fetch;
    this.project = new ProjectClient(baseUrl, fetchImpl);
    this.task = new TaskClient(baseUrl, fetchImpl);
  }
}
