// Code generated by pocketknife from the "Reading Tracker" manifest (app id "reading_tracker", schema version 1).
// DO NOT EDIT — regenerate from the manifest instead.

export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", `${field}:${op}:${String(value)}`);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? `?${qs}` : "";
}

// --- entity: book ---

export interface Book {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  title: string;
  author: string | null;
  rating: number | null;
  done: boolean | null;
  finished_at: ISODateTime | null;
}

export interface BookCreateInput {
  title: string;
  author?: string | null;
  rating?: number | null;
  done?: boolean | null;
  finished_at?: ISODateTime | null;
}

export interface BookUpdateInput {
  title?: string;
  author?: string | null;
  rating?: number | null;
  done?: boolean | null;
  finished_at?: ISODateTime | null;
}

export type BookFilterableField = "id" | "created_at" | "updated_at" | "title" | "author" | "rating" | "done" | "finished_at";

export type BookSortField = BookFilterableField | `-${BookFilterableField}`;

export interface BookListParams {
  filter?: Array<readonly [BookFilterableField, FilterOp, string | number | boolean]>;
  sort?: BookSortField[];
  limit?: number;
  offset?: number;
}

export class BookClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: BookCreateInput): Promise<Book> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/reading_tracker/book", input);
  }

  get(id: string): Promise<Book> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/reading_tracker/book/${encodeURIComponent(id)}`);
  }

  list(params?: BookListParams): Promise<ListResult<Book>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/reading_tracker/book${buildQuery(params)}`);
  }

  update(id: string, input: BookUpdateInput): Promise<Book> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/reading_tracker/book/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/reading_tracker/book/${encodeURIComponent(id)}`);
  }

}

export class ReadingTrackerClient {
  readonly book: BookClient;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "";
    const fetchImpl = options.fetch ?? fetch;
    this.book = new BookClient(baseUrl, fetchImpl);
  }
}
