// Generates a minimal but real TypeScript client surface from a manifest
// that has already passed structural + semantic validation. Shaped after
// (but not a port of) the production generator in client/generate.go: the
// same preamble runtime support, the same per-entity Row/CreateInput/
// UpdateInput/ListParams shapes, and the same CRUD method surface gated by
// each entity's enabled operations. The builder authors its frontend against
// this surface, never against raw fetch calls.

import type { AppManifest, Entity, Field } from "./manifest-types.js";
import { entityAllows, fieldHasDefault } from "./manifest-types.js";

const PREAMBLE = `export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", \`\${field}:\${op}:\${String(value)}\`);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? \`?\${qs}\` : "";
}

`;

export function generateClient(manifest: AppManifest): string {
  const parts: string[] = [];
  parts.push(
    `// Code generated by the pocketknife agent's stub validator from the ${JSON.stringify(manifest.app.name)} manifest (app id ${JSON.stringify(manifest.app.id)}, schema version ${manifest.app.version}).\n`,
  );
  parts.push("// DO NOT EDIT — regenerate from the manifest instead.\n\n");
  parts.push(PREAMBLE);

  for (const entity of manifest.entities) {
    parts.push(writeEntity(manifest, entity));
  }

  parts.push(writeRootClient(manifest));

  return parts.join("");
}

function fieldTSType(entity: Entity, field: Field): string {
  switch (field.type) {
    case "text":
    case "reference":
      return "string";
    case "datetime":
      return "ISODateTime";
    case "integer":
    case "real":
      return "number";
    case "boolean":
      return "boolean";
    case "enum":
      return enumTypeName(entity, field);
    default:
      return "unknown";
  }
}

function outputFieldType(entity: Entity, field: Field): string {
  const t = fieldTSType(entity, field);
  return field.required ? t : `${t} | null`;
}

function writeEntity(manifest: AppManifest, entity: Entity): string {
  const typeName = pascalCase(entity.name);
  const b: string[] = [];
  b.push(`// --- entity: ${entity.name} ---\n\n`);

  for (const field of entity.fields) {
    if (field.type === "enum") {
      b.push(`export type ${enumTypeName(entity, field)} = ${enumLiteralUnion(field.values)};\n\n`);
    }
  }

  b.push(`export interface ${typeName} {\n`);
  b.push("  id: string;\n");
  b.push("  created_at: ISODateTime;\n");
  b.push("  updated_at: ISODateTime;\n");
  for (const field of entity.fields) {
    b.push(`  ${field.name}: ${outputFieldType(entity, field)};\n`);
  }
  b.push("}\n\n");

  if (entityAllows(entity, "create")) {
    b.push(writeInputType(entity, `${typeName}CreateInput`, true));
  }
  if (entityAllows(entity, "update")) {
    b.push(writeInputType(entity, `${typeName}UpdateInput`, false));
  }
  if (entityAllows(entity, "read")) {
    b.push(writeListTypes(entity, typeName));
  }

  b.push(writeEntityClient(manifest, entity, typeName));

  return b.join("");
}

function writeInputType(entity: Entity, name: string, forCreate: boolean): string {
  const b: string[] = [];
  b.push(`export interface ${name} {\n`);
  for (const field of entity.fields) {
    let t = fieldTSType(entity, field);
    if (!field.required) {
      t += " | null";
    }
    const mandatory = forCreate && field.required === true && !fieldHasDefault(field);
    b.push(mandatory ? `  ${field.name}: ${t};\n` : `  ${field.name}?: ${t};\n`);
  }
  b.push("}\n\n");
  return b.join("");
}

function writeListTypes(entity: Entity, typeName: string): string {
  const fields = ["id", "created_at", "updated_at", ...entity.fields.map((f) => f.name)];
  const quoted = fields.map((f) => JSON.stringify(f));
  const fieldUnion = `${typeName}FilterableField`;

  const b: string[] = [];
  b.push(`export type ${fieldUnion} = ${quoted.join(" | ")};\n\n`);
  b.push(`export type ${typeName}SortField = ${fieldUnion} | \`-\${${fieldUnion}}\`;\n\n`);
  b.push(`export interface ${typeName}ListParams {\n`);
  b.push(`  filter?: Array<readonly [${fieldUnion}, FilterOp, string | number | boolean]>;\n`);
  b.push(`  sort?: ${typeName}SortField[];\n`);
  b.push("  limit?: number;\n");
  b.push("  offset?: number;\n");
  b.push("}\n\n");
  return b.join("");
}

function writeEntityClient(manifest: AppManifest, entity: Entity, typeName: string): string {
  const className = `${typeName}Client`;
  const base = `/apps/${manifest.app.id}/${entity.name}`;
  const b: string[] = [];

  b.push(`export class ${className} {\n`);
  b.push("  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}\n\n");

  if (entityAllows(entity, "create")) {
    b.push(`  create(input: ${typeName}CreateInput): Promise<${typeName}> {\n`);
    b.push(`    return request(this.baseUrl, this.fetchImpl, "POST", ${JSON.stringify(base)}, input);\n`);
    b.push("  }\n\n");
  }
  if (entityAllows(entity, "read")) {
    b.push(`  get(id: string): Promise<${typeName}> {\n`);
    b.push(`    return request(this.baseUrl, this.fetchImpl, "GET", \`${base}/\${encodeURIComponent(id)}\`);\n`);
    b.push("  }\n\n");

    b.push(`  list(params?: ${typeName}ListParams): Promise<ListResult<${typeName}>> {\n`);
    b.push(`    return request(this.baseUrl, this.fetchImpl, "GET", \`${base}\${buildQuery(params)}\`);\n`);
    b.push("  }\n\n");
  }
  if (entityAllows(entity, "update")) {
    b.push(`  update(id: string, input: ${typeName}UpdateInput): Promise<${typeName}> {\n`);
    b.push(
      `    return request(this.baseUrl, this.fetchImpl, "PATCH", \`${base}/\${encodeURIComponent(id)}\`, input);\n`,
    );
    b.push("  }\n\n");
  }
  if (entityAllows(entity, "delete")) {
    b.push(`  delete(id: string): Promise<void> {\n`);
    b.push(`    return request(this.baseUrl, this.fetchImpl, "DELETE", \`${base}/\${encodeURIComponent(id)}\`);\n`);
    b.push("  }\n\n");
  }
  b.push("}\n\n");
  return b.join("");
}

function writeRootClient(manifest: AppManifest): string {
  const className = `${pascalCase(manifest.app.id)}Client`;
  const b: string[] = [];
  b.push(`export class ${className} {\n`);
  for (const entity of manifest.entities) {
    b.push(`  readonly ${entity.name}: ${pascalCase(entity.name)}Client;\n`);
  }
  b.push("\n  constructor(options: ClientOptions = {}) {\n");
  b.push("    const baseUrl = options.baseUrl ?? \"\";\n");
  b.push("    const fetchImpl = options.fetch ?? fetch;\n");
  for (const entity of manifest.entities) {
    b.push(`    this.${entity.name} = new ${pascalCase(entity.name)}Client(baseUrl, fetchImpl);\n`);
  }
  b.push("  }\n");
  b.push("}\n");
  return b.join("");
}

function enumTypeName(entity: Entity, field: Field): string {
  return `${pascalCase(entity.name)}${pascalCase(field.name)}`;
}

function enumLiteralUnion(values: string[]): string {
  return values.map((v) => JSON.stringify(v)).join(" | ");
}

function pascalCase(name: string): string {
  return name
    .split("_")
    .filter((p) => p.length > 0)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
}
