// Code generated by pocketknife from the "Training" manifest (app id "workouts", schema version 1).
// DO NOT EDIT — regenerate from the manifest instead.

export type ISODateTime = string;

export type FilterOp = "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "like";

export interface ApiErrorBody {
  code: string;
  message: string;
  details?: unknown;
}

export class ApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly details?: unknown;

  constructor(status: number, body: ApiErrorBody) {
    super(body.message);
    this.name = "ApiError";
    this.status = status;
    this.code = body.code;
    this.details = body.details;
  }
}

export interface ListResult<T> {
  data: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ClientOptions {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchImpl: typeof fetch,
  method: string,
  path: string,
  body?: unknown,
): Promise<T> {
  const res = await fetchImpl(baseUrl + path, {
    method,
    headers: body !== undefined ? { "Content-Type": "application/json" } : undefined,
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (res.status === 204) {
    return undefined as T;
  }
  const text = await res.text();
  const data: unknown = text.length > 0 ? JSON.parse(text) : undefined;
  if (!res.ok) {
    const envelope = data as { error?: ApiErrorBody } | undefined;
    throw new ApiError(res.status, envelope?.error ?? { code: "unknown_error", message: res.statusText });
  }
  return data as T;
}

interface RawListParams {
  filter?: Array<readonly [string, FilterOp, string | number | boolean]>;
  sort?: readonly string[];
  limit?: number;
  offset?: number;
}

function buildQuery(params?: RawListParams): string {
  if (!params) return "";
  const q = new URLSearchParams();
  for (const [field, op, value] of params.filter ?? []) {
    q.append("filter", `${field}:${op}:${String(value)}`);
  }
  for (const s of params.sort ?? []) {
    q.append("sort", s);
  }
  if (params.limit !== undefined) q.set("limit", String(params.limit));
  if (params.offset !== undefined) q.set("offset", String(params.offset));
  const qs = q.toString();
  return qs.length > 0 ? `?${qs}` : "";
}

// --- entity: workout ---

export type WorkoutType = "hyrox" | "strength" | "running" | "mixed" | "other";

export interface Workout {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  date: ISODateTime;
  title: string | null;
  type: WorkoutType | null;
  total_seconds: number | null;
  rpe: number | null;
  bodyweight_kg: number | null;
  completed: boolean | null;
  notes: string | null;
}

export interface WorkoutCreateInput {
  date: ISODateTime;
  title?: string | null;
  type?: WorkoutType | null;
  total_seconds?: number | null;
  rpe?: number | null;
  bodyweight_kg?: number | null;
  completed?: boolean | null;
  notes?: string | null;
}

export interface WorkoutUpdateInput {
  date?: ISODateTime;
  title?: string | null;
  type?: WorkoutType | null;
  total_seconds?: number | null;
  rpe?: number | null;
  bodyweight_kg?: number | null;
  completed?: boolean | null;
  notes?: string | null;
}

export type WorkoutFilterableField = "id" | "created_at" | "updated_at" | "date" | "title" | "type" | "total_seconds" | "rpe" | "bodyweight_kg" | "completed" | "notes";

export type WorkoutSortField = WorkoutFilterableField | `-${WorkoutFilterableField}`;

export interface WorkoutListParams {
  filter?: Array<readonly [WorkoutFilterableField, FilterOp, string | number | boolean]>;
  sort?: WorkoutSortField[];
  limit?: number;
  offset?: number;
}

export class WorkoutClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: WorkoutCreateInput): Promise<Workout> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/workouts/workout", input);
  }

  get(id: string): Promise<Workout> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/workouts/workout/${encodeURIComponent(id)}`);
  }

  list(params?: WorkoutListParams): Promise<ListResult<Workout>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/workouts/workout${buildQuery(params)}`);
  }

  update(id: string, input: WorkoutUpdateInput): Promise<Workout> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/workouts/workout/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/workouts/workout/${encodeURIComponent(id)}`);
  }

}

// --- entity: exercise ---

export type ExerciseKind = "run" | "hyrox_station" | "strength" | "cardio" | "mobility" | "other";

export type ExerciseStation = "ski_erg" | "sled_push" | "sled_pull" | "burpee_broad_jump" | "row" | "farmers_carry" | "sandbag_lunges" | "wall_balls";

export interface Exercise {
  id: string;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  workout: string | null;
  position: number | null;
  kind: ExerciseKind;
  name: string | null;
  station: ExerciseStation | null;
  sets: number | null;
  reps: number | null;
  weight_kg: number | null;
  distance_m: number | null;
  seconds: number | null;
  rest_seconds: number | null;
  personal_best: boolean | null;
}

export interface ExerciseCreateInput {
  workout?: string | null;
  position?: number | null;
  kind: ExerciseKind;
  name?: string | null;
  station?: ExerciseStation | null;
  sets?: number | null;
  reps?: number | null;
  weight_kg?: number | null;
  distance_m?: number | null;
  seconds?: number | null;
  rest_seconds?: number | null;
  personal_best?: boolean | null;
}

export interface ExerciseUpdateInput {
  workout?: string | null;
  position?: number | null;
  kind?: ExerciseKind;
  name?: string | null;
  station?: ExerciseStation | null;
  sets?: number | null;
  reps?: number | null;
  weight_kg?: number | null;
  distance_m?: number | null;
  seconds?: number | null;
  rest_seconds?: number | null;
  personal_best?: boolean | null;
}

export type ExerciseFilterableField = "id" | "created_at" | "updated_at" | "workout" | "position" | "kind" | "name" | "station" | "sets" | "reps" | "weight_kg" | "distance_m" | "seconds" | "rest_seconds" | "personal_best";

export type ExerciseSortField = ExerciseFilterableField | `-${ExerciseFilterableField}`;

export interface ExerciseListParams {
  filter?: Array<readonly [ExerciseFilterableField, FilterOp, string | number | boolean]>;
  sort?: ExerciseSortField[];
  limit?: number;
  offset?: number;
}

export class ExerciseClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch) {}

  create(input: ExerciseCreateInput): Promise<Exercise> {
    return request(this.baseUrl, this.fetchImpl, "POST", "/apps/workouts/exercise", input);
  }

  get(id: string): Promise<Exercise> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/workouts/exercise/${encodeURIComponent(id)}`);
  }

  list(params?: ExerciseListParams): Promise<ListResult<Exercise>> {
    return request(this.baseUrl, this.fetchImpl, "GET", `/apps/workouts/exercise${buildQuery(params)}`);
  }

  update(id: string, input: ExerciseUpdateInput): Promise<Exercise> {
    return request(this.baseUrl, this.fetchImpl, "PATCH", `/apps/workouts/exercise/${encodeURIComponent(id)}`, input);
  }

  delete(id: string): Promise<void> {
    return request(this.baseUrl, this.fetchImpl, "DELETE", `/apps/workouts/exercise/${encodeURIComponent(id)}`);
  }

}

export class WorkoutsClient {
  readonly workout: WorkoutClient;
  readonly exercise: ExerciseClient;

  constructor(options: ClientOptions = {}) {
    const baseUrl = options.baseUrl ?? "";
    const fetchImpl = options.fetch ?? fetch;
    this.workout = new WorkoutClient(baseUrl, fetchImpl);
    this.exercise = new ExerciseClient(baseUrl, fetchImpl);
  }
}
